[package]
name = "mouse-click"
version = "0.1.0"
authors = ["luke-zhou"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
